# Mesh and weather files
max_volume_path:             "examples/test_inputs/basic_perimeter_block/maxVolume.ply"  # PLY of the full volume envelope
test_surface_path:           "examples/test_inputs/basic_perimeter_block/testSrfs.ply"  # PLY of surfaces to sample
epw_path:                    "examples/GRC_Athens.167160_IWEC.epw"  # Weather data file (or set USC_EPW_PATH env var)

# Output
out_dir:                     "examples/test_outputs/user_config_run"  # Where carved meshes go
final_mesh_format: ply        # Final mesh format. One of {'ply','obj','stl','glb'}
# Carving mode: time-based, irradiance, benefit, daylight, tilted_plane, or radiative_cooling [experimental]
mode:           'benefit'

# Analysis period (depends on used mode and what you're trying to achieve)
start_month:    10   #10
start_day:      15   #15
start_hour:     7    #7
end_month:      4    #4  
end_day:        15   #15
end_hour:       19   #19

# Dew point settings for radiative cooling
dew_point_celsius: 14.0    # Night-time dew-point in °C for radiative_cooling.
bliss_k:          1.8      # Empirical angular‐attenuation constant (Bliss 1961) for radiative_cooling.

# Voxel grid and sampling
voxel_size:     2.0    # length of voxel cube edge in m
grid_step:      1.0    # spacing between sample points in m
ray_length:     300.0  # max ray cast distance in m
min_altitude:   5.0    # ignore low sun angles
margin_frac:    0.01   # extra margin around mesh
ray_batch_size: 0  # 0 = auto-tune based on GPU VRAM

# Cleanup and smoothing
apply_smoothing: false # apply smoothing? False returns the raw carved mesh
min_voxels:     300   # drop tiny clusters
min_face_count: 100   # drop small fragments
smooth_iters:   2    #number of smoothing iterations

# Thresholding and scoring for weighted carving
threshold: 'carve_fraction'  # 'headtail', 'carve_fraction', or a numeric value. For time-based/tilted_plane, use an integer (violation count).
carve_fraction: 0.7 #

# Benefit mode settings (used when mode: benefit)
balance_temperature: 20.0
balance_offset: 2.0

# Plane-method (choose exactly one of the following two keys when mode: tilted_plane)
# either a single number or a list of 8 numbers for each orientation octant [N, NE, E, SE, S, SW, W, NW]
tilted_plane_angle_deg: 45.0      # angle for planar carving, or list like: [30, 27, 24, 24, 27, 30, 30, 27]  

# Diagnostics and devices
diagnostics: true  # write extra exports
device: 'cuda' # 'auto', 'cpu', or 'cuda'
